export const ACTION_TYPES_POST = {
  FETCH_START: "FETCH_START",
  FETCH_SUCCESS: "FETCH_SUCCESS",
  FETCH_ERROR: "FETCH_ERROR",
};

export const ACTION_TYPES_FORM = {
  CHANGE_INPUT: "CHANGE_INPUT",
  ADD_TAG: "ADD_TAG",
  REMOVE_TAG: "REMOVE_TAG",
  INCREASE: "INCREASE",
  DECREASE: "DECREASE",
};

export const ACTION_TYPES_LOGIN = {
  LOGIN_START: "LOGIN_START",
  LOGIN_SUCCESS: "LOGIN_START",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT: "LOGOUT",
};
